#This playbook was written for bitbucket, hopefully it works for github
#Note that an SSH alias is not needed as the ssh key is been specified

- name: clone or pull git repo
  git: repo={{ repo_source }}
       dest={{ repo_dest_path }}
       executable=/usr/bin/git
       accept_hostkey=true
       force=yes
       key_file=/root/.ssh/gitprovider-deploy
       version=master
  when: repo_enabled
