#Note that an SSH alias is not needed as the ssh key is been specified

- name: clone or pull git repo (Symfony)
  git: repo={{ repo_symfony_source }}
       dest={{ repo_symfony_dest_path }}
       executable=/usr/bin/git
       accept_hostkey=true
       force=yes
       key_file=/root/.ssh/gitprovider.symfony.deploy
       version=master
  when: repo_enabled
  tags:
    - release-symfony

- name: clone or pull git repo (front)
  git: repo={{ repo_front_source }}
       dest={{ repo_front_dest_path }}
       executable=/usr/bin/git
       accept_hostkey=true
       force=yes
       key_file=/root/.ssh/gitprovider.front.deploy
       version=master
  when: repo_enabled
  tags:
    - release-front
