#You will need to log into bitbucket/Github interface and install the deployment keys there
#https://confluence.atlassian.com/bitbucket/use-deployment-keys-294486051.html

#techincally this public key is not needed on the server but will copy it anyway
- name: setup git provider deployment key
  action: template src={{ item }}.j2 dest=~/.ssh/{{ item }} mode=600
  when: repo_enabled
  with_items:
    - gitprovider.front.deploy
    - gitprovider.front.deploy.pub
    - gitprovider.symfony.deploy
    - gitprovider.symfony.deploy.pub

- name: delete intended repo folder if it exists (Symfony)
  file: path={{ repo_symfony_dest_path }} state=absent
  when: repo_enabled

- name: delete intended repo folder if it exists (front)
  file: path={{ repo_front_dest_path }} state=absent
  when: repo_enabled

