# mysql56

- name: Install MySQL community release repository
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present

- name: Install mysql56 packages
  yum: name={{ item }} state=latest
  with_flattened:
        - MySQL-python
        - mysql-community-server
        - mysql-community-libs
        - mysql-community-devel
        - mysql-community-bench

- name: Start mysqld now!
  service: name=mysqld state=started enabled=true

- name: Update mysql root password for all root accounts
  mysql_user: name=root host=localhost password="{{ mysql_password }}"

#This will setup so when you run "mysql" from the terminal, you are not asked for the password
- name: Add .my-password.cnf to /root/.my.cnf
  action: template src=my-password.cnf.j2 dest=/root/.my.cnf

