# mysql56

# mysql_install_server will determine if the Mysql server should be install. You may be using an external
# Mysql server, and dont want to install it. The MySQL will be installed eitherway

- name: Install MySQL client only
  yum: name=mysql state=present
  when: not mysql_install_server

- name: Install MySQL community release repository
  yum: name=http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm state=present
  when: mysql_install_server

- name: Install mysql56 packages
  yum: name={{ item }} state=latest
  with_flattened:
        - MySQL-python
        - mysql-community-server
        - mysql-community-libs
        - mysql-community-devel
        - mysql-community-bench
  when: mysql_install_server

- name: Start mysqld now!
  service: name=mysqld state=started enabled=true
  when: mysql_install_server

- name: Update mysql root password for all root accounts
  mysql_user: name=root host=localhost password="{{ mysql_password }}"
  when: mysql_install_server

#This will setup so when you run "mysql" from the terminal, you are not asked for the password
- name: setup /root/.my.cnf
  action: template src=my.cnf.j2 dest=/root/.my.cnf

