# mysql56

- name: Install MySQL community release repository
  shell: rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm

- name: Install mysql56 packages
  yum: name={{ item }} state=latest
  with_flattened:
        - MySQL-python
        - mysql-community-server
        - mysql-community-libs
        - mysql-community-devel
        - mysql-community-bench

- name: Allow mysqld to be started after reboot
  shell: chkconfig mysqld on

- name: Start mysqld now!
  shell: service mysqld start

- name: Update mysql root password for all root accounts
  mysql_user: name=root host=localhost password="{{ mysql_password }}"

- name: Add .my-password.cnf to /root/.my.cnf
  action: template src=my-password.cnf.j2 dest=/root/.my.cnf
  #Sam's Notes: This will setup so when you run "mysql" from the terminal, you are not asked for the password
