#NOTE: this will only create password file to actually make basic auth start to work.
# However there are other things you will need to do to make Basic Auth work.
# You can use the ansible variables basic_auth_front_vhost and basic_auth_api_vhost
#
# Or you could place an .htaccess file inside the folder you would like to protect
#this .htaccess file should be something like
# AuthType Basic
# AuthName "Authentication Required"
# AuthUserFile "/etc/htpasswd/.htpasswd"
# Require valid-user


- name: install python-passlib needed for ansible htpasswd module
  yum: name=python-passlib state=latest

- name: Remove basic auth passowrd file if it exists
  file: path=/etc/htpasswd/.htpasswd state=absent

- name: Create basic auth password file
  htpasswd: create=yes state=present path=/etc/htpasswd/.htpasswd name={{ basic_auth_user }} password={{ basic_auth_password }}
