- name: install python-passlib needed for ansible htpasswd module
  yum: name=python-passlib state=latest

- name: Remove basic auth passowrd file if it exists
  file: path=/etc/htpasswd/.htpasswd state=absent

- name: Create basic auth password file
  htpasswd: create=yes state=present path=/etc/htpasswd/.htpasswd name={{ basic_auth_user }} password={{ basic_auth_password }}

- name: setup basic auth in apache
  action: template src=basic-auth.conf.j2 dest=/etc/httpd/conf.d/basic-auth.conf mode=644
