# php56

#https://support.rackspace.com/how-to/install-epel-and-additional-repositories-on-centos-and-red-hat/
- name: install EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

#https://webtatic.com/packages/php56/
- name: install Webtatic EL
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: Install REMI repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable REMI repository
  ini_file: dest=/etc/yum.repos.d/remi.repo
            section=remi
            option=enabled
            value=1

- name: Enable REMI-php56 repository
  ini_file: dest=/etc/yum.repos.d/remi.repo
            section=remi-php56
            option=enabled
            value=1

#Start PHP packages
- name: Install php
  yum: name=php state=latest

- name: Install php-devel
  yum: name=php-devel state=latest

- name: Install php-common
  yum: name=php-common state=latest

- name: Install php-cli
  yum: name=php-cli state=latest

- name: Install php-pear
  yum: name=php-pear state=latest

- name: Install php-pdo
  yum: name=php-pdo state=latest

- name: Install php-mysql
  yum: name=php-mysql state=latest

- name: Install php-gd
  yum: name=php-gd state=latest

- name: Install php-mbstring
  yum: name=php-mbstring state=latest

- name: Install php-mcrypt
  yum: name=php-mcrypt state=latest

- name: Install php-xml
  yum: name=php-xml state=latest

- name: Install php-bcmath
  yum: name=php-bcmath state=latest

- name: Install php-stats
  yum: name=php-stats state=latest
#end PHP packages


#TODO need to install memcache, and the PHP extention
#http://www.liquidweb.com/kb/how-to-install-memcached-on-centos-7/
#http://www.liquidweb.com/kb/how-to-install-the-memcached-php-extension-on-centos-7/
#make sure that memcache starts automattically.

- name: Install nodejs
  yum: name=npm state=latest

- name: removing html folders which is not used
  file: path=/var/www/html state=absent

- name: Restart Apache
  service: name=httpd state=restarted
