# mysql56

#NOTE: With google cloud, we are using a decicated MySQL instance, so only install the MySQL client

- name: Install MySQL client only
  yum: name=mysql state=present
  when: not mysql_install_server

- name: Install MySQL community release repository
  yum: name=http://repo.mysql.com/mysql57-community-release-el7-9.noarch.rpm state=present
  when: mysql_install_server

- name: Install mysql packages
  yum: name={{ item }} state=latest
  with_flattened:
        - MySQL-python
        - mysql-community-server
        - mysql-community-libs
        - mysql-community-devel
        - mysql-community-bench
  when: mysql_install_server

- name: disable validate-password plugin
  vars:
    myCnfLine: 'validate-password=off #Disable this plugin, it was really annoying in dev environment, was forcing password to be set and the password policy was also relly strict'
  lineinfile: dest=/etc/my.cnf regexp="^validate-password.*" line={{myCnfLine}} state=present

- name: Start mysqld now!
  service: name=mysqld state=started enabled=true
  when: mysql_install_server

- name: Update mysql root password for all root accounts
  mysql_user: name=root host=localhost password="{{ mysql_password }}"
  when: mysql_install_server

#This will setup so when you run "mysql" from the terminal, you are not asked for the password
- name: setup /root/.my.cnf
  action: template src=my.cnf.j2 dest=/root/.my.cnf

