# playbook

- name: Install all necessary tools and set the environment ready
  hosts: all
  user: root

  roles:
    - common

- name: setup .bashrc file
  hosts: all
  user: root

  roles:
    - bashrc

- name: Install Apache web server and configure
  hosts: all
  user: root

  roles:
    - httpd

- name: Setup apache SSL
  hosts: all
  user: root

  roles:
    - role: httpd_ssl
      tags: ['ssl']

- name: Install and configure PHP 5.6 with required extentions
  hosts: all
  user: root

  roles:
    - php56

- name: PHP settings
  hosts: all
  user: root

  roles:
    - php_settings

- name: Install and configure MySQL
  hosts: all
  user: root

  roles:
    - mysql56

- name: Install composer
  hosts: all
  user: root

  roles:
    - composer

#You may chose to disable the installion of Git2 if its not needed as the installation takes a while.
- name: Install Git2
  hosts: all
  user: root

  roles:
    - role: git2
      tags: ['git2']
