- name: fetch php7-stats-module source code
  get_url: url=https://pecl.php.net/get/stats-2.0.3.tgz dest=/usr/tmp/php-stats.tgz

- name: expand php7-stats-module archive
  unarchive: src=/usr/tmp/php-stats.tgz dest=/usr/tmp copy=no

- name: run phpize --clean
  shell: phpize --clean chdir=/usr/tmp/stats-2.0.3

- name: run phpize
  shell: phpize chdir=/usr/tmp/stats-2.0.3

- name: run configure
  shell: ./configure chdir=/usr/tmp/stats-2.0.3

- name: run make
  shell: make chdir=/usr/tmp/stats-2.0.3

- name: run make
  shell: make install chdir=/usr/tmp/stats-2.0.3

- name: create stats.ini
  action: template src=stats.ini.j2 dest=/etc/php.d/stats.ini

- name: Restart Apache
  service: name=httpd state=restarted

